function student_navigation_popover(a,b){"preferences"==a?b?($(".preferences_element").addClass("filled"),$(".preferences_element span").addClass("icon-preferences-filled"),$(".preferences_element span").removeClass("icon-preferences-linear")):($(".preferences_element").removeClass("filled"),$(".preferences_element").addClass("active"),$(".preferences_element span").removeClass("icon-preferences-filled"),$(".preferences_element span").addClass("icon-preferences-linear")):"personal_details"==a?b?($(".personal_details_element").addClass("filled"),
$(".personal_details_element span").addClass("icon-personal-details-filled"),$(".personal_details_element span").removeClass("icon-personal-details-linear")):($(".personal_details_element").removeClass("filled"),$(".personal_details_element").addClass("active"),$(".personal_details_element span").removeClass("icon-personal-details-filled"),$(".personal_details_element span").addClass("icon-personal-details-linear"),profile_incomplete_student_navigation_popover("personal_details")):"education_details"==
a?b?($(".education_details_element").addClass("filled"),$(".education_details_element span").addClass("icon-education-details-filled"),$(".education_details_element span").removeClass("icon-education-details-linear"),$(".experiences_element a").attr("href","/student/work_experiences"),$(".skills_element a").attr("href","/student/skills"),$(".work_samples_element a").attr("href","/student/work_samples")):($(".education_details_element").removeClass("filled"),$(".education_details_element").addClass("active"),
$(".education_details_element span").removeClass("icon-education-details-filled"),$(".education_details_element span").addClass("icon-education-details-linear"),profile_incomplete_student_navigation_popover("education_details")):"experiences"==a||"other_experiences"==a?b?($(".experiences_element").addClass("filled"),$(".experiences_element span").addClass("icon-experiences-filled"),$(".experiences_element span").removeClass("icon-experiences-linear")):($(".experiences_element").removeClass("filled"),
$(".experiences_element").addClass("active"),$(".experiences_element span").removeClass("icon-experiences-filled"),$(".experiences_element span").addClass("icon-experiences-linear")):"work_samples"==a||"additional_details"==a?b?($(".work_samples_element").addClass("filled"),$(".work_samples_element span").addClass("icon-work-samples-filled"),$(".work_samples_element span").removeClass("icon-work-samples-linear")):($(".work_samples_element").removeClass("filled"),$(".work_samples_element").addClass("active"),
$(".work_samples_element span").removeClass("icon-work-samples-filled"),$(".work_samples_element span").addClass("icon-work-samples-linear")):"skills"==a&&(b?($(".skills_element").addClass("filled"),$(".skills_element span").addClass("icon-skills-filled"),$(".skills_element span").removeClass("icon-skills-linear")):($(".skills_element").removeClass("filled"),$(".skills_element").addClass("active"),$(".skills_element span").removeClass("icon-skills-filled"),$(".skills_element span").addClass("icon-skills-linear")))}
function profile_incomplete_student_navigation_popover(a){"personal_details"==a?($(".education_details_element").removeClass("active"),$(".education_details_element").removeClass("filled"),$(".education_details_element a").removeAttr("href"),$(".experiences_element a").removeAttr("href"),$(".skills_element a").removeAttr("href"),$(".work_samples_element a").removeAttr("href")):"education_details"==a&&($(".experiences_element a").removeAttr("href"),$(".skills_element a").removeAttr("href"),$(".work_samples_element a").removeAttr("href"));
$(".experiences_element").removeClass("active");$(".work_samples_element").removeClass("active");$(".skills_element").removeClass("active");$(".experiences_element").removeClass("filled");$(".work_samples_element").removeClass("filled");$(".skills_element").removeClass("filled")}
function updateStudentNavigationTabs(a){"preferences"==a?$("#preferencesTab").addClass("active"):"dashboard"==a?$("#applicationTab").addClass("active"):"resume"==a&&$("#resumeTab").addClass("active");$(".navTabItem").click(function(){if($(this).hasClass("active"))return!1;var a=$(this).attr("url");window.location=a})};$(document).ready(function(){load_applications(1);updateStudentNavigationTabs("dashboard");$("#next").click(function(a){a.preventDefault();parseInt($("#current_page_number").val())<parseInt($("#total_pages").val())&&(a=parseInt($("#current_page_number").val())+1,load_applications(a))});$("#prev").click(function(a){a.preventDefault();1<parseInt($("#current_page_number").val())&&(a=parseInt($("#current_page_number").val())-1,load_applications(a))});load_notification(notification_short_message,notification_message)});
var load_notification=function(a,b){if("undefined"!==typeof a&&0<a.length||"undefined"!==typeof b&&0<b.length){var c=""==b?" ":" <b class= 'dashboard_notification' >Know more</b>";$("#short_notification").html(a+c);$("#notifications_container").show();$("#notifications_container").addClass("alert");$("#notifications_container").addClass("alert-info")}};
function load_applications(a){a={page_number:a,sidx:"created_at",sord:"desc"};NProgress.start();$(".loading_image").show();$.ajax("/student/paginated_applications",{data:a,success:load_applications_success,error:onError,type:"POST"})}
var load_applications_success=function(a){try{NProgress.done(),a=JSON.parse(a),a.success?($(".loading_image").hide(),$("#current_page_number").val(a.current_page_number),$("#total_pages").val(a.total_pages),parseInt($("#current_page_number").val())>=parseInt($("#total_pages").val())?$("#next").parent().addClass("disabled"):$("#next").parent().removeClass("disabled"),1>=parseInt($("#current_page_number").val())?$("#prev").parent().addClass("disabled"):$("#prev").parent().removeClass("disabled"),$("#applications_tbody").html(a.view)):
throw_error(a.errorThrown)}catch(b){throw_error(b),NProgress.done(),$(".loading_image").hide()}};var user_email_input=$("#email").val();
$(document).ready(function(){subscription_form_validate();$(".email-field-subscribe").keyup(function(){var a=$("#subscribe-form").find("#email").val();user_email_input!==a&&(user_email_input=a,prompt_for_correct_email("subscribe-form","email"))});$(".email-field-subscribe-marketing-right").keyup(function(){var a=$("#subscribe-form").find("#email").val();user_email_input!==a&&(user_email_input=a,prompt_for_correct_email("subscribe-form","email"))});$(".subscribe-form-at-bottom-email").keyup(function(){var a=$("#subscribe-form-at-bottom").find("#email").val();
user_email_input!==a&&(user_email_input=a,prompt_for_correct_email("subscribe-form-at-bottom","email"))})});
function subscription_form_validate(){$("#subscribe-form").validate({onfocusout:function(a){this.element(a)},rules:{email:{required:!0,email:!0}},errorPlacement:function(a,b){a.insertAfter(b)},highlight:function(a){$(a).closest(".form-group").addClass("has-error");$(a).closest(".form-group").removeClass("has-success");$(a).closest("input").addClass("error");$(a).closest("input").removeClass("valid")},success:function(a){$(a).closest(".form-group").addClass("has-success");$(a).closest(".form-group").removeClass("has-error");
$(a).closest("input").addClass("valid");$(a).closest("input").removeClass("error")},submitHandler:function(){var a=$("#subscribe-form").serialize();NProgress.start();$(".loading_image").show();$.ajax("/subscribe/submit",{data:a,success:subscription_success,error:onError,type:"POST"});return!1}});$("#subscribe-form-popup").validate({rules:{email:{required:!0,email:!0}},errorPlacement:function(a,b){"email"===b.attr("name")?a.insertAfter("#but_subscription_form"):a.insertAfter(b)},highlight:function(a){$(a).closest(".form-group").addClass("has-error");
$(a).closest(".form-group").removeClass("has-success");$(a).closest("input").addClass("error");$(a).closest("input").removeClass("valid")},success:function(a){$(a).closest(".form-group").addClass("has-success");$(a).closest(".form-group").removeClass("has-error");$(a).closest("input").addClass("valid");$(a).closest("input").removeClass("error")},submitHandler:function(){var a=$("#subscribe-form-popup").serialize()+"&current_url="+window.location.href;NProgress.start();$(".loading_image").show();$.ajax("/subscribe/submit",
{data:a,success:subscription_success,error:onError,type:"POST"});return!1}});$("#subscribe-form-at-bottom").validate({onfocusout:function(a){this.element(a)},rules:{email:{required:!0,email:!0}},errorPlacement:function(a,b){a.insertAfter(b)},highlight:function(a){$(a).closest(".form-group").addClass("has-error");$(a).closest(".form-group").removeClass("has-success");$(a).closest("input").addClass("error");$(a).closest("input").removeClass("valid")},success:function(a){$(a).closest(".form-group").addClass("has-success");
$(a).closest(".form-group").removeClass("has-error");$(a).closest("input").addClass("valid");$(a).closest("input").removeClass("error")},submitHandler:function(){var a=$("#subscribe-form-at-bottom").serialize();NProgress.start();$(".loading_image").show();$.ajax("/subscribe/submit",{data:a,success:subscription_success,error:onError,type:"POST"});return!1}})}
var subscription_success=function(a){try{NProgress.done(),$(".subscription_alert").hide(),$("#email").val(""),$(".backdrop").hide(),a=JSON.parse(a),a.success?throw_success(a.successMsg,a.successPage):throw_error(a.errorThrown)}catch(b){throw_error(b),NProgress.done(),$(".loading_image").hide()}};var check_notification_flag=!0;
$(document).ready(function(){if("undefined"!==typeof notification_id&&""!=notification_id){var a=($("#notificaton_"+notification_id).offset()||{top:NaN}).top;isNaN(a)||(a=$("#notificaton_"+notification_id).offset().top,$("html, body").animate({scrollTop:a},1E3),save_notification&&store_notification(notification_id))}$(document).on("click","b.dashboard_notification",function(){$("#notification").html(notification_message);check_notification_flag&&store_notification(notification_id);$("#notification").slideToggle("slow",
function(){$(this).is(":visible")?$("b.dashboard_notification").html(" Hide"):$("b.dashboard_notification").html(" Know more")})});to_show_filters_matching_preferences_notification&&show_filters_matching_preferences_notification();$(document).on("click","#filters_matching_preferences_notification_close_button",function(){insert_filters_matching_preferences_notification()})});
function store_notification(a){$.ajax("/student/check_notification",{data:{notification_id:a},success:store_notification_success,error:onError,type:"POST"})}
var store_notification_success=function(a){try{NProgress.done(),a=JSON.parse(a),a.success?check_notification_flag=!1:throw_semi_error(a.errorThrown)}catch(b){throw_error(b),NProgress.done()}},show_filters_matching_preferences_notification=function(){$("#filters").popover({html:"true",trigger:"manual"}).popover("show");$("#to_show_internships_as_per_my_preferences").attr("disabled",!0);$("#matching_checkbox_preferences_link").click(function(){return!1});$("#matching_checkbox_preferences_link").css("cursor",
"default");$(".popover_overlay").show()};function insert_filters_matching_preferences_notification(){$.ajax("/student/insert_notification_by_name/to_show_internships_as_per_my_preferences_notification",{data:[],success:insert_filters_matching_preferences_notification_success,error:onError,type:"POST"})}
var insert_filters_matching_preferences_notification_success=function(a){try{a=JSON.parse(a),a.success?($("#filters").popover("hide"),$(".popover_overlay").hide(),$("#to_show_internships_as_per_my_preferences").attr("disabled",!1),$("#matching_checkbox_preferences_link").unbind("click"),$("#matching_checkbox_preferences_link").css("cursor","pointer"),to_show_filters_matching_preferences_notification=!1):throw_error(a.errorThrown,"/internships/")}catch(b){throw_error(b)}};